
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.1.0.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace mame_ao.source {
    using System;
    using Terminal.Gui;
    
    
    public partial class MameAOProcessor : Terminal.Gui.Window {
        
        private Terminal.Gui.Label label6;
        
        private Terminal.Gui.Label label7;
        
        private Terminal.Gui.Window window;
        
        private Terminal.Gui.ListView listView4;
        
        private Terminal.Gui.ListView listView5;
        
        private Terminal.Gui.Label label5;
        
        private Terminal.Gui.Label label4;
        
        private Terminal.Gui.Label label3;
        
        private Terminal.Gui.ListView listView3;
        
        private Terminal.Gui.ListView listView2;
        
        private Terminal.Gui.ListView listView1;
        
        private Terminal.Gui.TextField textField;
        
        private Terminal.Gui.Label label2;
        
        private Terminal.Gui.LineView lineView;
        
        private Terminal.Gui.TextField consoleHeading;
        
        private Terminal.Gui.Button button;
        
        private Terminal.Gui.Button button2;
        
        private void InitializeComponent() {
            this.button2 = new Terminal.Gui.Button();
            this.button = new Terminal.Gui.Button();
            this.consoleHeading = new Terminal.Gui.TextField();
            this.lineView = new Terminal.Gui.LineView();
            this.label2 = new Terminal.Gui.Label();
            this.textField = new Terminal.Gui.TextField();
            this.listView1 = new Terminal.Gui.ListView();
            this.listView2 = new Terminal.Gui.ListView();
            this.listView3 = new Terminal.Gui.ListView();
            this.label3 = new Terminal.Gui.Label();
            this.label4 = new Terminal.Gui.Label();
            this.label5 = new Terminal.Gui.Label();
            this.listView5 = new Terminal.Gui.ListView();
            this.listView4 = new Terminal.Gui.ListView();
            this.window = new Terminal.Gui.Window();
            this.label7 = new Terminal.Gui.Label();
            this.label6 = new Terminal.Gui.Label();
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Visible = true;
            this.Modal = false;
            this.IsMdiContainer = false;
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Rounded;
            this.Border.Effect3D = true;
            this.Border.Effect3DBrush = null;
            this.Border.DrawMarginFrame = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = "Press Ctrl+Q to quit";
            this.label6.Width = 15;
            this.label6.Height = 1;
            this.label6.X = 53;
            this.label6.Y = 0;
            this.label6.Visible = true;
            this.label6.Data = "label6";
            this.label6.Text = "Heya";
            this.label6.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label6);
            this.label7.Width = 15;
            this.label7.Height = 1;
            this.label7.X = 86;
            this.label7.Y = 0;
            this.label7.Visible = true;
            this.label7.Data = "label7";
            this.label7.Text = "Heya";
            this.label7.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label7);
            this.window.Width = 48;
            this.window.Height = 15;
            this.window.X = 1;
            this.window.Y = 1;
            this.window.Visible = true;
            this.window.Modal = false;
            this.window.IsMdiContainer = false;
            this.window.Data = "window";
            this.window.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.window.Border.Effect3D = false;
            this.window.Border.Effect3DBrush = null;
            this.window.Border.DrawMarginFrame = true;
            this.window.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.window.Title = "";
            this.Add(this.window);
            this.listView4.Width = 32;
            this.listView4.Height = 17;
            this.listView4.X = 53;
            this.listView4.Y = 1;
            this.listView4.Visible = true;
            this.listView4.Data = "listView4";
            this.listView4.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.listView4.Source = new Terminal.Gui.ListWrapper(new string[] {
                        "Item1",
                        "Item2",
                        "Item3"});
            this.listView4.AllowsMarking = true;
            this.listView4.AllowsMultipleSelection = true;
            this.Add(this.listView4);
            this.listView5.Width = 31;
            this.listView5.Height = 17;
            this.listView5.X = 86;
            this.listView5.Y = 1;
            this.listView5.Visible = true;
            this.listView5.Data = "listView5";
            this.listView5.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.listView5.Source = new Terminal.Gui.ListWrapper(new string[] {
                        "Item1",
                        "Item2",
                        "Item3"});
            this.listView5.AllowsMarking = true;
            this.listView5.AllowsMultipleSelection = true;
            this.Add(this.listView5);
            this.label5.Width = 15;
            this.label5.Height = 1;
            this.label5.X = 56;
            this.label5.Y = 19;
            this.label5.Visible = true;
            this.label5.Data = "label5";
            this.label5.Text = "Heya";
            this.label5.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label5);
            this.label4.Width = 15;
            this.label4.Height = 1;
            this.label4.X = 76;
            this.label4.Y = 19;
            this.label4.Visible = true;
            this.label4.Data = "label4";
            this.label4.Text = "Heya";
            this.label4.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label4);
            this.label3.Width = 15;
            this.label3.Height = 1;
            this.label3.X = 96;
            this.label3.Y = 19;
            this.label3.Visible = true;
            this.label3.Data = "label3";
            this.label3.Text = "Heya";
            this.label3.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label3);
            this.listView3.Width = 19;
            this.listView3.Height = 8;
            this.listView3.X = 56;
            this.listView3.Y = 20;
            this.listView3.Visible = true;
            this.listView3.Data = "listView3";
            this.listView3.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.listView3.Source = new Terminal.Gui.ListWrapper(new string[] {
                        "Item1",
                        "Item2",
                        "Item3"});
            this.listView3.AllowsMarking = true;
            this.listView3.AllowsMultipleSelection = true;
            this.Add(this.listView3);
            this.listView2.Width = 19;
            this.listView2.Height = 8;
            this.listView2.X = 76;
            this.listView2.Y = 20;
            this.listView2.Visible = true;
            this.listView2.Data = "listView2";
            this.listView2.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.listView2.Source = new Terminal.Gui.ListWrapper(new string[] {
                        "Item1",
                        "Item2",
                        "Item3",
                        "Item1",
                        "Item2",
                        "Item3"});
            this.listView2.AllowsMarking = true;
            this.listView2.AllowsMultipleSelection = true;
            this.Add(this.listView2);
            this.listView1.Width = 16;
            this.listView1.Height = 8;
            this.listView1.X = 96;
            this.listView1.Y = 20;
            this.listView1.Visible = true;
            this.listView1.Data = "listView1";
            this.listView1.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.listView1.Source = new Terminal.Gui.ListWrapper(new string[] {
                        "Item1",
                        "Item2",
                        "Item3"});
            this.listView1.AllowsMarking = true;
            this.listView1.AllowsMultipleSelection = true;
            this.Add(this.listView1);
            this.textField.Width = 10;
            this.textField.Height = 1;
            this.textField.X = 1;
            this.textField.Y = 21;
            this.textField.Visible = true;
            this.textField.Secret = false;
            this.textField.Data = "textField";
            this.textField.Text = "";
            this.textField.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.textField);
            this.label2.Width = 17;
            this.label2.Height = 1;
            this.label2.X = 1;
            this.label2.Y = 23;
            this.label2.Visible = true;
            this.label2.Data = "label2";
            this.label2.Text = "Heya";
            this.label2.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label2);
            this.lineView.Width = 8;
            this.lineView.Height = 1;
            this.lineView.X = 31;
            this.lineView.Y = 23;
            this.lineView.Visible = true;
            this.lineView.Data = "lineView";
            this.lineView.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.lineView.LineRune = '─';
            this.lineView.Orientation = Terminal.Gui.Graphs.Orientation.Horizontal;
            this.Add(this.lineView);
            this.consoleHeading.Width = 10;
            this.consoleHeading.Height = 1;
            this.consoleHeading.X = 1;
            this.consoleHeading.Y = 25;
            this.consoleHeading.Visible = true;
            this.consoleHeading.Secret = false;
            this.consoleHeading.Data = "consoleHeading";
            this.consoleHeading.Text = "xxxxx";
            this.consoleHeading.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.consoleHeading);
            this.button.Width = 12;
            this.button.Height = 1;
            this.button.X = 1;
            this.button.Y = 27;
            this.button.Visible = true;
            this.button.Data = "button";
            this.button.Text = "Download";
            this.button.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.button.IsDefault = false;
            this.Add(this.button);
            this.button2.Width = 17;
            this.button2.Height = 1;
            this.button2.X = 14;
            this.button2.Y = 27;
            this.button2.Visible = true;
            this.button2.Data = "button2";
            this.button2.Text = "Start Torrent";
            this.button2.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.button2.IsDefault = false;
            this.Add(this.button2);
        }
    }
}
