name: .NET Framework  

on:  
  push:  
    branches: [main]  
  pull_request:  
    branches: [main]  

jobs:  
  build:  
    runs-on: ubuntu-latest  

    steps:  
    - uses: actions/checkout@v2  
    - name: Setup .NET Framework  
      uses: actions/setup-dotnet@v1  
      with:  
        dotnet-version: '4.8'  
    - name: Restore dependencies  
      run: nuget restore  
    - name: Build  
      run: msbuild /t:build  
    - name: Test  
      run: vstest.console.exe
